### PR TITLE
Fix for issue #2

### LINKED ISSUE #2: The link to the file is not relative path which cuase link broke.
The current implementation just directly use file.src path as link in a.href. I just did quick fix myself by pass file.dest to function buildDataStructure and resolve the relative file path and therefore pass to addFileLocationToDirectoryStructure. Function addFileLocationToDirectoryStructure  is the place set path which I replace filepath by my relativefilepath. 

It look like ugly fix, but not sure which is proper way.

### PR DESCRIPTION
**Pull request by tjdownes**
Fixes #2. I do believe there is more work to be done here with this specific issue, but this will allow many users to fix relative pathing issues.

### CODE REVIEW

**Comment by stephendeyoung** [comment]
Thanks very much for doing this TJ. Are you able to add a test for this feature?

**Comment by tjdownes** [comment]
I'm not terribly experienced with unit testing, or nodeunit, but I'll take a look at it later this evening and see if I can get one running.

**Comment by tjdownes** [comment]
@stephendeyoung I am working on getting your unit tests running. I am receiving the following exception from your tests

`
Error: Missing helper: 'recurse'
    at Object.<anonymous> (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\base.js:48:11)
    at program8 (eval at <anonymous> (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\compiler\compiler.js:579:23), <anonymous>:64:129)
    at Object.program [as fn] (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\runtime.js:77:14)
    at Object.<anonymous> (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\base.js:143:20)
    at program1 (eval at <anonymous> (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\compiler\compiler.js:579:23), <anonymous>:17:26)
    at program (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\runtime.js:77:14)
    at Object.<anonymous> (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\base.js:116:21)
    at Object.eval (eval at <anonymous> (X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\compiler\compiler.js:579:23), <anonymous>:71:25)
    at X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\runtime.js:38:33
    at X:\Projects\grunt-directory-to-html\grunt-directory-to-html\node_modules\handlebars\lib\handlebars\compiler\compiler.js:1294:21
`

I am assuming this helper is either a custom helper not included or a helper I need to add to the package, but since there are no docs and Google turned up nothing on this helper, I'll need your guidance.

**Comment by stephendeyoung** [comment]
Sorry TJ I'm not getting that error when running the tests. How are you running the tests? You've done an `npm install` right?

**Comment by tjdownes** [comment]
I have run the npm install. I believe this may be a handlebars helper you are using that is not included in the project dependencies.

**Comment by tjdownes** [comment]
I have tried testing using the command line:
`nodeunit test/to-html-test.js`

as well as via IntelliJ

**Comment by tjdownes** [comment]
I just noticed this is failing in the handlebars_option test, using the "tasks/templates/html-structure.hbs" template, which includes the recurse helper on line 19

**Comment by stephendeyoung** [comment]
The `recurse` helper is defined here:

https://github.com/stephendeyoung/grunt-directory-to-html/blob/master/tasks/to-html.js#L42

So it should be working. 

Do any of the tests pass?

**Comment by tjdownes** [comment]
image

**Comment by stephendeyoung** [comment]
Do you get the same error when you run `npm test`? You might be having problems because you're trying to run the test file directly. The tests are supposed to be run through Grunt.

**Comment by tjdownes** [comment]
When I run grunt test, which is what I assume you meant, all the tests fail. The test failures are odd and don't give me any indication of why they are failing, which is why I chose to run nodeunit directly.

Example:

'Running "nodeunit:tests" (nodeunit) task
Testing to-html-test.jsFFFFF.FFFF

> > to_html - default_options
> > Message: should create a basic html template from a simple directory structure
> > Error: '\n<ul>\n  <li>\n    <h2><a href="test/fixtures/basic/modules/another_test_link/index.html">Another test link</a>\n    </h2>\n  </li>\n  <li>\n    <h2><a href="test/fixtures/basic/modules/test_link/index.html">Test link</a>\n    </h2>\n  </li>\n</ul>' == '\r\n<ul>\r\n  <li>\r\n    <h2><a href="test/fixtures/basic/modules/another_test_link/index.html">Another test link</a>\r\n    </h2>\r\n  </li>\r\n  <li>\r\n    <h2><a href="test/fixtures/basic/modules/test_link/index.html">Test link</a>\r\n    </h2>\r\n  </li>\r\n</ul>'
> > at Object.exports.to_html.default_options (test\to-html-test.js:33:10)'

**Comment by tjdownes** [comment]
Actually, now that i have pasted the HTML, it looks like the reason it's failing is because the generated tests add a line return. Do you work on a Mac, per chance? I suspect this is the difference between Mac and Windows generating those files, in which case, the tests will always fail

**Comment by tjdownes** [comment]
We decided to move forward using another task. Feel free to use my code for yours.

**Pull request closed without merging**
